
export const ORDER_STATUS ={
    PENDING: "PENDING",
    CANCEL: "CANCEL",
    REJECTED: "REJECTED",
    DISPATCHED: "DISPATCHED",
    COMPLETED: "COMPLETED",
    INPROGRESS: "INPROGRESS",
    PROCESSING: "PROCESSING",
    READ: "READY"
}