export const TRANSACTION_TYPE = {
  RECEIVE: 'RECEIVE',
  TRANSFER: 'TRANSFER',
  PAYOUT: 'PAYOUT',
  SEND: 'SEND'
};

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED'
};